name: Contract Guard

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run contract check
        env:
          PORTPULSE_BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
        run: |
          python3 scripts/check_openapi_contract.py
  smoke:
    runs-on: ubuntu-latest
    needs: check-openapi
    steps:
      - name: Smoke snapshot + dwell
        env:
          BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
          API_KEY:  ${{ secrets.PORTPULSE_API_KEY }}
        run: |
          set -euo pipefail
          curl -sS -H "X-API-Key: $API_KEY" "$BASE_URL/v1/ports/USLAX/snapshot" | jq .
          curl -sS -H "X-API-Key: $API_KEY" "$BASE_URL/v1/ports/USLAX/dwell?days=14" | jq .