name: Docs Build & Headers Smoke

on:
  pull_request:
    paths:
      - "docs-site/**"
      - ".github/workflows/docs-build-and-smoke.yml"
      - "scripts/smoke_docs_headers.sh"
  push:
    branches: [ main ]
    paths:
      - "docs-site/**"
      - ".github/workflows/docs-build-and-smoke.yml"
      - "scripts/smoke_docs_headers.sh"
  workflow_dispatch:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Build docs
        run: pnpm -C docs-site build

      - name: Start local server
        run: |
          npx http-server "docs-site/build" -p 8090 >/dev/null 2>&1 &
          echo $! > server.pid
          sleep 1

      - name: Headers smoke (local)
        run: bash scripts/smoke_docs_headers.sh "http://127.0.0.1:8090"

      - name: Upload build artifact (for preview)
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs-site/build
          if-no-files-found: error

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi