name: PortPulse ETL

on:
  workflow_dispatch:
  schedule:
    # 每天 02:40 UTC（北京时间 10:40）
    - cron: "40 2 * * *"

permissions:
  contents: read

jobs:
  etl:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PYTHONUNBUFFERED: "1"
      TZ: "UTC"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 端口侧 ETL（你仓库现有脚本）
      - name: Run Port ETL
        run: python -u etl/etl_port_lax.py

      # 贸易侧 ETL（你仓库现有脚本）
      - name: Run Trade ETL
        run: python -u etl/etl_uncomtrade.py

      # 简单健康/数据冒烟
      - name: Smoke test API
        run: |
          curl -fsSL https://portpulse01-production.up.railway.app/v1/health
          curl -fsSL -H "X-API-Key: dev_key_123" \
            https://portpulse01-production.up.railway.app/v1/ports/USLAX/snapshot \
            | head -c 200 || true
      - name: Create issue on failure
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "ETL failed - ${{ github.run_id }}"
          body: "Check run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"