cat > .github/workflows/etl.yml <<'YAML'
name: PortPulse ETL

on:
  workflow_dispatch: {}
  schedule:
    # 每天 02:40 UTC 跑一次（北京时间 10:40）
    - cron: "40 2 * * *"

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PYTHONUNBUFFERED: "1"
      TZ: "UTC"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # —— 使用仓库里已经存在的脚本 —— #
      - name: Run LAX dwell ETL
        run: python etl/etl_port_lax.py

      - name: Run UN Comtrade HS imports ETL (4202)
        run: python etl/etl_uncomtrade.py

      # 如已新增 NYC 的脚本，再解开下面两行：
      # - name: Run NYC dwell ETL
      #   run: python etl/etl_port_nyc.py
YAML