name: PortPulse ETL

on:
  schedule:
    - cron: "0 3 * * *"   # 每天 03:00 UTC 自动跑（北京时区=UTC+8，对应每天 11:00）
  workflow_dispatch:       # 允许在 Actions 页手动一键运行

jobs:
  run-etl:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install asyncpg httpx python-dateutil

      - name: Make daily port snapshots
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python etl/etl_snapshot.py

      - name: Fetch HS4202 from UN Comtrade (optional)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          COMTRADE_API_KEY: ${{ secrets.COMTRADE_API_KEY }}
        run: |
          python etl/etl_uncomtrade.py || echo "skip if no key"
