name: P1 Smoke
on:
  push:
  workflow_dispatch:
  schedule: [{cron: "*/30 * * * *"}]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq curl
      - name: Run smoke
        env:
          BASE: https://api.useportpulse.com
          KEY: dev_demo_123
        run: |
          bash scripts/p1_smoke.sh "$BASE" "$KEY"
