# .github/workflows/release.yml
name: Release Gate
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run Gate
        env:
          BASE: https://api.useportpulse.com
          API_KEY: ${{ secrets.PORTPULSE_LIVE_KEY }}
        run: |
          chmod +x scripts/*.sh
          scripts/ci_gate-1.sh