name: Selfcheck

on:
  schedule:
    - cron: '0 9 * * 1-5'  # 周一至周五上午9点（UTC时间）
  workflow_dispatch:

jobs:
  selfcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import app.main (cold import guard)
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module("app.main")
          print("import app.main OK")
          PY
      - name: Run selfcheck
        run: python -m pytest tests/selfcheck.py -v
      - name: Notify Slack (always)
        if: always() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL || '' }}
        run: scripts/notify_ops.sh