name: Smoke
on:
  schedule:
    - cron: "*/30 * * * *"   # 每 30 分钟
  workflow_dispatch:        # 手动触发
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke tests
        run: bash scripts/smoke.sh
        env:
          API_KEY: ${{ secrets.PORTPULSE_API_KEY }}
          BASE_URL: https://api.useportpulse.com
          PORT_OVERVIEW: USLAX
          PORT_ALERTS: USNYC
          ALERT_WINDOW: 14d
