name: Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      # （可留可删）如果你的自检脚本不依赖 Python，可以去掉这步以加快速度
      # - uses: actions/setup-python@v5
      #   with: { python-version: '3.11' }

      - name: Make selfcheck executable
        run: chmod +x scripts/selfcheck.sh

      - name: Run API selfcheck (retry once)
        env:
          BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
          API_KEY: ${{ secrets.PORTPULSE_API_KEY }}
        run: |
          set -e
          bash scripts/selfcheck.sh 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" \
          || (echo "retry once..." | tee -a "$GITHUB_STEP_SUMMARY"; sleep 10; bash scripts/selfcheck.sh 2>&1 | tee -a "$GITHUB_STEP_SUMMARY")