name: Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run smoke.sh
        env:
          API_KEY: ${{ secrets.PORTPULSE_API_KEY }}
          BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
          PORT_OVERVIEW: ${{ secrets.PORTPULSE_PORT_OVERVIEW }}
          PORT_ALERTS: ${{ secrets.PORTPULSE_PORT_ALERTS }}
          ALERT_WINDOW: ${{ secrets.PORTPULSE_ALERT_WINDOW }}
        run: |
          bash scripts/smoke.sh || (echo "retry once..." && sleep 10 && bash scripts/smoke.sh)