name: Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # ✅ 关键：在 job 级别声明 env，所有步骤都会继承
    env:
      BASE_URL: https://api.useportpulse.com              # 如需放到 Secret 也行，见下
      API_KEY: ${{ secrets.PORTPULSE_API_KEY }}           # 你已有这个 secret
      # 可选：Slack，不用就别配
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Selfcheck (server p95 guard)
        run: bash scripts/selfcheck.sh

      - name: Run API selfcheck (retry once)
        run: |
          bash scripts/selfcheck.sh || (echo "retry once..." && sleep 10 && bash scripts/selfcheck.sh)

      # 可选：有 Slack 再开；没有就删掉这个 step
      - name: Notify to Slack
        if: always() && env.SLACK_WEBHOOK_URL != ''   # 没配就跳过
        run: |
          bash scripts/selfcheck.sh | tee selfcheck.out
          STATUS=GREEN TITLE="PortPulse selfcheck (CI)" LOG_FILE=selfcheck.out \
            bash scripts/notify_ops.sh