name: Smoke
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Make selfcheck executable
        run: chmod +x scripts/selfcheck.sh

      # 首次执行，作为“服务端 p95 守门”（x-response-time-ms）
      - name: Selfcheck (server p95 guard)
        env:
          BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
          API_KEY:  ${{ secrets.PORTPULSE_API_KEY }}
          # 严格的“服务端阈值”（x-response-time-ms），默认 300ms
          SLOW_SERVER_MS: "300"
          # E2E 仅做告警，不影响退出码（脚本内已处理）
          SLOW_E2E_MS: "2500"
        run: bash scripts/selfcheck.sh

      # 失败时重试一次（避免偶发网络抖动）
      - name: Run API selfcheck (retry once)
        if: failure()
        env:
          BASE_URL: ${{ secrets.PORTPULSE_BASE_URL }}
          API_KEY:  ${{ secrets.PORTPULSE_API_KEY }}
          SLOW_SERVER_MS: "300"
          SLOW_E2E_MS: "2500"
        run: |
          echo "retry once..." && sleep 10
          bash scripts/selfcheck.sh