name: Sync openapi.json to Pages
on:
  schedule: [{cron: "*/30 * * * *"}]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest openapi.json from prod
        run: curl -fsSL https://api.useportpulse.com/openapi.json -o docs/openapi.json
      - name: Commit & push if changed
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add docs/openapi.json
          git diff --cached --quiet || git commit -m "docs: update openapi.json from prod"
          git push
